### ISSUE TITLE
Try naming complex conditions

### ISSUE THREAD

**Issue by oliverjam** [fac20/week-10-JT#4]
https://github.com/fac20/week-10-JT/blob/bfc11dea7de82affa0529fac77570e0e39fcd26d/src/components/quiz/index.js#L85

I find it can be helpful to create named variables for conditions that have a few parts to them. That way you don't have to parse them in your brain to figure out when this branch of code will run. E.g.
```js
const shouldShowDrinks = drinkData && !success && !failed;
```
or something

**Comment by jenndroid** [comment]
thanks, refactored
